"""`ferry config edit` — open the config file in $EDITOR, creating it if absent."""

from __future__ import annotations

import os
from pathlib import Path

import click

from ferry.config import (
    ConfigError,
    default_config_path,
    load_config,
)
from ferry.config.loader import ENV_CONFIG_PATH

_STUB_TEMPLATE = """\
# ferry config — see DESIGN.md for the full key reference.
# Generated by `ferry config edit`. Edit freely.

[romm]
url = "https://romm.example.tld"
# api_key = "rmm_..."   # or export FERRY_ROMM_API_KEY in your shell profile

# [destination] tells ferry where to put downloaded ROMs.
# Run `ferry detect` to see what presets match your machine.
#
# [destination]
# preset = "retrodeck-flatpak"

# [sync] picks what to sync. At least one source must be non-empty.
#
# [sync]
# collections = ["Steam Deck"]
# platforms = ["gba", "snes"]
# delete_on_remove = false
"""


@click.group("config")
def config_group() -> None:
    """Inspect and edit ferry's configuration file."""


@config_group.command("edit")
@click.pass_context
def edit(ctx: click.Context) -> None:
    """Open ferry's config.toml in $EDITOR ($VISUAL takes precedence)."""
    path = _resolve_config_path(ctx)

    created = False
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_STUB_TEMPLATE)
        created = True
        click.echo(f"created template at {path}")

    click.edit(filename=str(path))

    try:
        load_config(path)
    except ConfigError as e:
        click.echo("", err=True)
        click.echo(f"warning: config is invalid after editing: {e}", err=True)
        if created:
            click.echo(
                "(the template needs [romm].api_key — fill it in or export FERRY_ROMM_API_KEY)",
                err=True,
            )


def _resolve_config_path(ctx: click.Context) -> Path:
    explicit = ctx.obj.get("config_path") if ctx.obj else None
    if explicit is not None:
        return explicit
    env_path = os.environ.get(ENV_CONFIG_PATH)
    if env_path:
        return Path(env_path)
    return default_config_path()
