"""Generate the launch-hook wrapper script + custom_systems XML overrides.

`ferry install-launch-hooks` (CLI in `cli/launch_hooks.py`) drives this
module to produce two artifacts:

1. **Wrapper shell script** at `$XDG_DATA_HOME/ferry/launch-hook.sh`.
   Called by ES-DE's wrapped `<command>` with arguments
   `<rom-path> <pre|post> [emu-exit-code]`. Sets up the host-path env
   vars (so ferry inside RetroDECK's sandbox uses host config/state),
   logs to a single file (truncated on `pre`, appended on `post` —
   one game session = one log file), and exits with the emulator's
   exit code on the `post` call so ES-DE sees the right status.

2. **Managed block** inside the user's
   `~/ES-DE/custom_systems/es_systems.xml` (or RetroDECK's flatpak
   path). For each `<system>` in the bundled es_systems.xml, we
   generate a parallel entry that wraps each `<command>` with calls
   to the wrapper script. Everything else (`<name>`, `<fullname>`,
   `<path>`, `<extension>`, `<platform>`, `<theme>`) is copied
   verbatim. User-added custom systems outside our managed block are
   preserved across re-runs.

Idempotent: re-running install regenerates only our managed block and
the wrapper script. Uninstall removes both.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

logger = logging.getLogger(__name__)

MANAGED_BLOCK_BEGIN = (
    "<!-- BEGIN ferry-managed (do not edit; regenerate via `ferry install-launch-hooks`) -->"
)
MANAGED_BLOCK_END = "<!-- END ferry-managed -->"

# Match the managed block so we can replace it on re-install / strip it
# on uninstall. `re.DOTALL` makes `.` match newlines (the block spans
# multiple lines). Greedy by default, but our markers are unique so
# greediness is moot.
_MANAGED_BLOCK_RE = re.compile(
    re.escape(MANAGED_BLOCK_BEGIN) + r".*?" + re.escape(MANAGED_BLOCK_END),
    re.DOTALL,
)

# Default wrapper script location (under XDG_DATA_HOME/ferry/).
_WRAPPER_FILENAME = "launch-hook.sh"


@dataclass(frozen=True, slots=True, kw_only=True)
class WrapperConfig:
    """Inputs the install command bakes into the generated wrapper script.

    `ferry_bin` is the absolute path to the ferry binary on the host.
    `host_*` are the host-side env paths the script exports inside the
    flatpak sandbox so ferry uses the user's actual config/state. `log_path`
    is None when logging is disabled (script writes to /dev/null instead).
    """

    ferry_bin: Path
    host_home: Path
    host_xdg_config: Path
    host_xdg_state: Path
    host_xdg_cache: Path
    log_path: Path | None


def default_wrapper_path(env: dict | None = None) -> Path:
    """`$XDG_DATA_HOME/ferry/launch-hook.sh`, default `~/.local/share/ferry/...`."""
    env = env if env is not None else os.environ
    base = env.get("XDG_DATA_HOME")
    root = Path(base) if base else Path.home() / ".local" / "share"
    return root / "ferry" / _WRAPPER_FILENAME


def render_wrapper_script(config: WrapperConfig) -> str:
    """Return the wrapper shell script content as a string.

    Truncates `$LOG` on `pre`, appends on `post` — so a session's pre +
    post output sits in one file, replaced on next session. When
    `log_path` is None, output goes to /dev/null (logging disabled).
    """
    log_target = str(config.log_path) if config.log_path else "/dev/null"
    return f"""#!/bin/bash
# ferry launch-hook wrapper — generated by `ferry install-launch-hooks`.
# Re-run that command to regenerate. Do not edit by hand.

set +e  # never block the launch chain on internal errors

# Host-path env overrides — when this script runs from inside RetroDECK's
# flatpak (which redirects $HOME to the sandboxed config dir), these
# point ferry at the user's actual config/state files on the host
# filesystem (accessible via --filesystem=host).
export HOME={_shell_quote(str(config.host_home))}
export XDG_CONFIG_HOME={_shell_quote(str(config.host_xdg_config))}
export XDG_STATE_HOME={_shell_quote(str(config.host_xdg_state))}
export XDG_CACHE_HOME={_shell_quote(str(config.host_xdg_cache))}

FERRY={_shell_quote(str(config.ferry_bin))}
LOG={_shell_quote(log_target)}

ROM="$1"
PHASE="$2"
EMU_EC="${{3:-0}}"

mkdir -p "$(dirname "$LOG")" 2>/dev/null || true

case "$PHASE" in
  pre)
    {{
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] PRE rom=$ROM"
      "$FERRY" sync --rom "$ROM" 2>&1
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] PRE done"
    }} > "$LOG"
    ;;
  post)
    {{
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] POST rom=$ROM emu_exit=$EMU_EC"
      "$FERRY" sync --rom "$ROM" 2>&1
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] POST done"
    }} >> "$LOG"
    ;;
  *)
    echo "ferry launch-hook: unknown phase '$PHASE' (expected 'pre' or 'post')" >&2
    ;;
esac

exit "$EMU_EC"
"""


def _shell_quote(s: str) -> str:
    """Quote a string for safe inclusion in a shell script literal.

    Wraps in single quotes; escapes embedded single quotes via the
    `'\\''` idiom. Sufficient for paths.
    """
    return "'" + s.replace("'", "'\\''") + "'"


# ---------------------------------------------------------------------------
# XML generation — wrapping bundled <system> entries
# ---------------------------------------------------------------------------


def render_managed_block(bundled_xml_path: Path, wrapper_path: Path) -> str:
    """Read the bundled es_systems.xml and return the managed-block content.

    Output is a string of `<system>` elements (no XML decl, no
    `<systemList>` wrapper) ready to be embedded between the
    BEGIN/END markers. Each system mirrors the bundled entry verbatim
    except for `<command>` elements, which are wrapped with calls to
    `wrapper_path` for pre/post sync.
    """
    tree = ET.parse(bundled_xml_path)
    root = tree.getroot()
    if root.tag != "systemList":
        raise ValueError(
            f"unexpected root element {root.tag!r} in {bundled_xml_path} (expected 'systemList')"
        )

    out: list[str] = []
    for system in root.findall("system"):
        out.append(_render_wrapped_system(system, wrapper_path))
    return "\n".join(out)


def _render_wrapped_system(system_el: ET.Element, wrapper_path: Path) -> str:
    """Serialize one wrapped <system> entry.

    Children in this order (matching ES-DE's bundled style): name,
    fullname, path, extension, command (one or more), platform, theme.
    Unknown children are passed through verbatim — defensive in case
    RetroDECK adds new ones.
    """
    parts: list[str] = ["    <system>"]
    # Standard ES-DE child order — we keep RetroDECK's verbatim ordering
    # by iterating in source order rather than re-sorting.
    for child in system_el:
        if child.tag == "command":
            parts.append(_render_wrapped_command(child, wrapper_path))
        else:
            parts.append(_render_simple_element(child, indent=8))
    parts.append("    </system>")
    return "\n".join(parts)


def _render_wrapped_command(command_el: ET.Element, wrapper_path: Path) -> str:
    """Wrap one <command> with pre/post calls to the wrapper script.

    `%ROM%` is ES-DE's substitution token for the absolute ROM path;
    we forward it as-is to the wrapper. `$?` captures the emulator's
    exit code so the final wrapper call exits with it (ES-DE sees the
    right status).
    """
    label = command_el.get("label")
    label_attr = f' label="{_xml_escape_attr(label)}"' if label else ""
    original = (command_el.text or "").strip()
    wrapper = str(wrapper_path)
    wrapped = (
        f"{_shell_quote(wrapper)} %ROM% pre ; {original} ; {_shell_quote(wrapper)} %ROM% post $?"
    )
    return f"        <command{label_attr}>{_xml_escape_text(wrapped)}</command>"


def _render_simple_element(el: ET.Element, *, indent: int) -> str:
    """Serialize a leaf element (no nested children). Matches RetroDECK style."""
    pad = " " * indent
    text = _xml_escape_text((el.text or "").strip())
    return f"{pad}<{el.tag}>{text}</{el.tag}>"


def _xml_escape_text(s: str) -> str:
    """Escape `&`, `<`, `>` for inclusion in element text."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _xml_escape_attr(s: str) -> str:
    """Escape for inclusion in an attribute value (also escapes quotes)."""
    return _xml_escape_text(s).replace('"', "&quot;")


# ---------------------------------------------------------------------------
# Managed-block file surgery
# ---------------------------------------------------------------------------


def install_managed_block(custom_path: Path, managed_content: str) -> None:
    """Write the managed block into `custom_path`.

    - File doesn't exist → create with `<systemList>` + managed block.
    - File exists with managed block → replace block in place.
    - File exists without managed block → insert block before `</systemList>`.

    Hand-edited content outside the managed block is preserved.
    """
    block = f"  {MANAGED_BLOCK_BEGIN}\n{managed_content}\n  {MANAGED_BLOCK_END}"

    custom_path.parent.mkdir(parents=True, exist_ok=True)

    if custom_path.exists():
        text = custom_path.read_text()
        if MANAGED_BLOCK_BEGIN in text:
            new_text = _MANAGED_BLOCK_RE.sub(_escape_re_replacement(block), text)
        else:
            new_text = _insert_before_close(text, block)
    else:
        new_text = f'<?xml version="1.0"?>\n<systemList>\n{block}\n</systemList>\n'

    custom_path.write_text(new_text)


def uninstall_managed_block(custom_path: Path) -> bool:
    """Strip the managed block from `custom_path`. Returns True if removed.

    If the resulting file has no remaining `<system>` entries (just an
    empty `<systemList>`), the file is left in place — ES-DE handles
    empty system lists fine, and removing the file would risk taking
    out structure the user wants to keep.
    """
    if not custom_path.is_file():
        return False
    text = custom_path.read_text()
    if MANAGED_BLOCK_BEGIN not in text:
        return False
    new_text = _MANAGED_BLOCK_RE.sub("", text)
    # Tidy up: remove any blank line left where the block sat.
    new_text = re.sub(r"\n[ \t]*\n[ \t]*\n", "\n\n", new_text)
    custom_path.write_text(new_text)
    return True


def _insert_before_close(text: str, block: str) -> str:
    """Insert `block` immediately before the closing `</systemList>` tag."""
    close_tag = "</systemList>"
    idx = text.rfind(close_tag)
    if idx == -1:
        raise ValueError(
            "custom_systems/es_systems.xml is missing a closing </systemList> tag; "
            "ferry won't modify malformed files"
        )
    return text[:idx] + block + "\n" + text[idx:]


def _escape_re_replacement(s: str) -> str:
    """Escape backslashes in `s` so `re.sub` treats it literally."""
    return s.replace("\\", "\\\\")


# ---------------------------------------------------------------------------
# Drift snapshot — track what we wrote so `status` / `sync` can detect
# both upstream drift (bundled file changed under us) and local drift
# (user edited our managed block).
# ---------------------------------------------------------------------------

_SNAPSHOT_FILENAME = "launch-hooks.snapshot.json"
_SNAPSHOT_VERSION = 1


@dataclass(frozen=True, slots=True, kw_only=True)
class Snapshot:
    """Persisted record of what `install-launch-hooks` last wrote.

    `bundled_path` and `custom_systems_path` pin the install we wrote
    against — `status` and `sync` re-hash these and compare to the
    stored SHAs to detect drift. Stored at
    `$XDG_STATE_HOME/ferry/launch-hooks.snapshot.json`.
    """

    bundled_path: Path
    bundled_sha256: str
    custom_systems_path: Path
    managed_block_sha256: str
    installed_at: str  # ISO8601 UTC string
    version: int = _SNAPSHOT_VERSION


@dataclass(frozen=True, slots=True, kw_only=True)
class HookStatus:
    """Drift report comparing a `Snapshot` against current disk state.

    `current_bundled_sha` is None when the bundled file no longer exists
    (e.g., RetroDECK update relocated it). `current_block_sha` is None
    when the managed block was removed from custom_systems (e.g., user
    deleted the file or hand-stripped the block).
    """

    snapshot: Snapshot
    current_bundled_sha: str | None
    current_block_sha: str | None

    @property
    def bundled_present(self) -> bool:
        return self.current_bundled_sha is not None

    @property
    def block_present(self) -> bool:
        return self.current_block_sha is not None

    @property
    def upstream_drift(self) -> bool:
        """Bundled file's content changed since install."""
        return self.bundled_present and self.current_bundled_sha != self.snapshot.bundled_sha256

    @property
    def local_drift(self) -> bool:
        """Managed block's content changed since install (user edited it)."""
        return self.block_present and self.current_block_sha != self.snapshot.managed_block_sha256

    @property
    def is_clean(self) -> bool:
        """Both files present and both SHAs match what we wrote."""
        return (
            self.bundled_present
            and self.block_present
            and not self.upstream_drift
            and not self.local_drift
        )


def default_snapshot_path(env: dict | None = None) -> Path:
    """`$XDG_STATE_HOME/ferry/launch-hooks.snapshot.json`."""
    env = env if env is not None else os.environ
    base = env.get("XDG_STATE_HOME")
    root = Path(base) if base else Path.home() / ".local" / "state"
    return root / "ferry" / _SNAPSHOT_FILENAME


def compute_file_sha256(path: Path) -> str:
    """SHA-256 of a file's bytes. Streams in 64KB chunks."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(64 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def extract_managed_block(custom_path: Path) -> str | None:
    """Return the markers + body matched by `_MANAGED_BLOCK_RE`, or None.

    None when the file doesn't exist or contains no managed block.
    The returned substring is exactly what the SHA is computed over —
    `compute_managed_block_sha256` and the snapshot writer must agree
    on this so drift comparisons are stable.
    """
    if not custom_path.is_file():
        return None
    text = custom_path.read_text()
    match = _MANAGED_BLOCK_RE.search(text)
    return match.group(0) if match else None


def compute_managed_block_sha256(custom_path: Path) -> str | None:
    """SHA-256 of the managed block (markers + body), or None if absent."""
    block = extract_managed_block(custom_path)
    if block is None:
        return None
    return hashlib.sha256(block.encode("utf-8")).hexdigest()


def write_snapshot(path: Path, snapshot: Snapshot) -> None:
    """Serialize a Snapshot to JSON at `path` (parent dir created)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": snapshot.version,
        "bundled_path": str(snapshot.bundled_path),
        "bundled_sha256": snapshot.bundled_sha256,
        "custom_systems_path": str(snapshot.custom_systems_path),
        "managed_block_sha256": snapshot.managed_block_sha256,
        "installed_at": snapshot.installed_at,
    }
    path.write_text(json.dumps(payload, indent=2) + "\n")


def read_snapshot(path: Path) -> Snapshot | None:
    """Return the persisted Snapshot, or None when missing or unreadable.

    Treats malformed JSON / missing keys / unknown versions the same as
    "absent" — the user can re-run `install-launch-hooks` to rewrite a
    valid snapshot.
    """
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    try:
        version = int(data.get("version", _SNAPSHOT_VERSION))
        if version != _SNAPSHOT_VERSION:
            return None
        return Snapshot(
            bundled_path=Path(data["bundled_path"]),
            bundled_sha256=data["bundled_sha256"],
            custom_systems_path=Path(data["custom_systems_path"]),
            managed_block_sha256=data["managed_block_sha256"],
            installed_at=data["installed_at"],
            version=version,
        )
    except (KeyError, TypeError, ValueError):
        return None


def delete_snapshot(path: Path) -> bool:
    """Remove the snapshot file. Returns True iff it existed."""
    if path.is_file():
        path.unlink()
        return True
    return False


def make_snapshot(*, bundled_path: Path, custom_systems_path: Path) -> Snapshot:
    """Capture current bundled + managed-block state as a fresh Snapshot.

    Call this AFTER `install_managed_block` writes the file — both SHAs
    are computed by reading from disk, which guarantees they match what
    `extract_managed_block` / `compute_file_sha256` will produce on
    subsequent drift checks.
    """
    block_sha = compute_managed_block_sha256(custom_systems_path)
    if block_sha is None:
        raise ValueError(
            f"managed block not found in {custom_systems_path} — "
            "install_managed_block must run before make_snapshot."
        )
    return Snapshot(
        bundled_path=bundled_path,
        bundled_sha256=compute_file_sha256(bundled_path),
        custom_systems_path=custom_systems_path,
        managed_block_sha256=block_sha,
        installed_at=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )


def detect_drift(snapshot: Snapshot) -> HookStatus:
    """Compare snapshot against current disk state and report drift."""
    bundled_sha = (
        compute_file_sha256(snapshot.bundled_path) if snapshot.bundled_path.is_file() else None
    )
    block_sha = compute_managed_block_sha256(snapshot.custom_systems_path)
    return HookStatus(
        snapshot=snapshot,
        current_bundled_sha=bundled_sha,
        current_block_sha=block_sha,
    )
