"""Generate the launch-hook wrapper script + custom_systems XML overrides.

`ferry install-launch-hooks` (CLI in `cli/launch_hooks.py`) drives this
module to produce two artifacts:

1. **Wrapper shell script** at `$XDG_DATA_HOME/ferry/launch-hook.sh`.
   Called by ES-DE's wrapped `<command>` with arguments
   `<rom-path> <pre|post> [emu-exit-code]`. Sets up the host-path env
   vars (so ferry inside RetroDECK's sandbox uses host config/state),
   logs to a single file (truncated on `pre`, appended on `post` —
   one game session = one log file), and exits with the emulator's
   exit code on the `post` call so ES-DE sees the right status.

2. **Managed block** inside the user's
   `~/ES-DE/custom_systems/es_systems.xml` (or RetroDECK's flatpak
   path). For each `<system>` in the bundled es_systems.xml, we
   generate a parallel entry that wraps each `<command>` with calls
   to the wrapper script. Everything else (`<name>`, `<fullname>`,
   `<path>`, `<extension>`, `<platform>`, `<theme>`) is copied
   verbatim. User-added custom systems outside our managed block are
   preserved across re-runs.

Idempotent: re-running install regenerates only our managed block and
the wrapper script. Uninstall removes both.
"""

from __future__ import annotations

import logging
import os
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

MANAGED_BLOCK_BEGIN = (
    "<!-- BEGIN ferry-managed (do not edit; regenerate via `ferry install-launch-hooks`) -->"
)
MANAGED_BLOCK_END = "<!-- END ferry-managed -->"

# Match the managed block so we can replace it on re-install / strip it
# on uninstall. `re.DOTALL` makes `.` match newlines (the block spans
# multiple lines). Greedy by default, but our markers are unique so
# greediness is moot.
_MANAGED_BLOCK_RE = re.compile(
    re.escape(MANAGED_BLOCK_BEGIN) + r".*?" + re.escape(MANAGED_BLOCK_END),
    re.DOTALL,
)

# Default wrapper script location (under XDG_DATA_HOME/ferry/).
_WRAPPER_FILENAME = "launch-hook.sh"


@dataclass(frozen=True, slots=True, kw_only=True)
class WrapperConfig:
    """Inputs the install command bakes into the generated wrapper script.

    `ferry_bin` is the absolute path to the ferry binary on the host.
    `host_*` are the host-side env paths the script exports inside the
    flatpak sandbox so ferry uses the user's actual config/state. `log_path`
    is None when logging is disabled (script writes to /dev/null instead).
    """

    ferry_bin: Path
    host_home: Path
    host_xdg_config: Path
    host_xdg_state: Path
    host_xdg_cache: Path
    log_path: Path | None


def default_wrapper_path(env: dict | None = None) -> Path:
    """`$XDG_DATA_HOME/ferry/launch-hook.sh`, default `~/.local/share/ferry/...`."""
    env = env if env is not None else os.environ
    base = env.get("XDG_DATA_HOME")
    root = Path(base) if base else Path.home() / ".local" / "share"
    return root / "ferry" / _WRAPPER_FILENAME


def render_wrapper_script(config: WrapperConfig) -> str:
    """Return the wrapper shell script content as a string.

    Truncates `$LOG` on `pre`, appends on `post` — so a session's pre +
    post output sits in one file, replaced on next session. When
    `log_path` is None, output goes to /dev/null (logging disabled).
    """
    log_target = str(config.log_path) if config.log_path else "/dev/null"
    return f"""#!/bin/bash
# ferry launch-hook wrapper — generated by `ferry install-launch-hooks`.
# Re-run that command to regenerate. Do not edit by hand.

set +e  # never block the launch chain on internal errors

# Host-path env overrides — when this script runs from inside RetroDECK's
# flatpak (which redirects $HOME to the sandboxed config dir), these
# point ferry at the user's actual config/state files on the host
# filesystem (accessible via --filesystem=host).
export HOME={_shell_quote(str(config.host_home))}
export XDG_CONFIG_HOME={_shell_quote(str(config.host_xdg_config))}
export XDG_STATE_HOME={_shell_quote(str(config.host_xdg_state))}
export XDG_CACHE_HOME={_shell_quote(str(config.host_xdg_cache))}

FERRY={_shell_quote(str(config.ferry_bin))}
LOG={_shell_quote(log_target)}

ROM="$1"
PHASE="$2"
EMU_EC="${{3:-0}}"

mkdir -p "$(dirname "$LOG")" 2>/dev/null || true

case "$PHASE" in
  pre)
    {{
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] PRE rom=$ROM"
      "$FERRY" sync --rom "$ROM" 2>&1
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] PRE done"
    }} > "$LOG"
    ;;
  post)
    {{
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] POST rom=$ROM emu_exit=$EMU_EC"
      "$FERRY" sync --rom "$ROM" 2>&1
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] POST done"
    }} >> "$LOG"
    ;;
  *)
    echo "ferry launch-hook: unknown phase '$PHASE' (expected 'pre' or 'post')" >&2
    ;;
esac

exit "$EMU_EC"
"""


def _shell_quote(s: str) -> str:
    """Quote a string for safe inclusion in a shell script literal.

    Wraps in single quotes; escapes embedded single quotes via the
    `'\\''` idiom. Sufficient for paths.
    """
    return "'" + s.replace("'", "'\\''") + "'"


# ---------------------------------------------------------------------------
# XML generation — wrapping bundled <system> entries
# ---------------------------------------------------------------------------


def render_managed_block(bundled_xml_path: Path, wrapper_path: Path) -> str:
    """Read the bundled es_systems.xml and return the managed-block content.

    Output is a string of `<system>` elements (no XML decl, no
    `<systemList>` wrapper) ready to be embedded between the
    BEGIN/END markers. Each system mirrors the bundled entry verbatim
    except for `<command>` elements, which are wrapped with calls to
    `wrapper_path` for pre/post sync.
    """
    tree = ET.parse(bundled_xml_path)
    root = tree.getroot()
    if root.tag != "systemList":
        raise ValueError(
            f"unexpected root element {root.tag!r} in {bundled_xml_path} (expected 'systemList')"
        )

    out: list[str] = []
    for system in root.findall("system"):
        out.append(_render_wrapped_system(system, wrapper_path))
    return "\n".join(out)


def _render_wrapped_system(system_el: ET.Element, wrapper_path: Path) -> str:
    """Serialize one wrapped <system> entry.

    Children in this order (matching ES-DE's bundled style): name,
    fullname, path, extension, command (one or more), platform, theme.
    Unknown children are passed through verbatim — defensive in case
    RetroDECK adds new ones.
    """
    parts: list[str] = ["    <system>"]
    # Standard ES-DE child order — we keep RetroDECK's verbatim ordering
    # by iterating in source order rather than re-sorting.
    for child in system_el:
        if child.tag == "command":
            parts.append(_render_wrapped_command(child, wrapper_path))
        else:
            parts.append(_render_simple_element(child, indent=8))
    parts.append("    </system>")
    return "\n".join(parts)


def _render_wrapped_command(command_el: ET.Element, wrapper_path: Path) -> str:
    """Wrap one <command> with pre/post calls to the wrapper script.

    `%ROM%` is ES-DE's substitution token for the absolute ROM path;
    we forward it as-is to the wrapper. `$?` captures the emulator's
    exit code so the final wrapper call exits with it (ES-DE sees the
    right status).
    """
    label = command_el.get("label")
    label_attr = f' label="{_xml_escape_attr(label)}"' if label else ""
    original = (command_el.text or "").strip()
    wrapper = str(wrapper_path)
    wrapped = (
        f"{_shell_quote(wrapper)} %ROM% pre ; {original} ; {_shell_quote(wrapper)} %ROM% post $?"
    )
    return f"        <command{label_attr}>{_xml_escape_text(wrapped)}</command>"


def _render_simple_element(el: ET.Element, *, indent: int) -> str:
    """Serialize a leaf element (no nested children). Matches RetroDECK style."""
    pad = " " * indent
    text = _xml_escape_text((el.text or "").strip())
    return f"{pad}<{el.tag}>{text}</{el.tag}>"


def _xml_escape_text(s: str) -> str:
    """Escape `&`, `<`, `>` for inclusion in element text."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _xml_escape_attr(s: str) -> str:
    """Escape for inclusion in an attribute value (also escapes quotes)."""
    return _xml_escape_text(s).replace('"', "&quot;")


# ---------------------------------------------------------------------------
# Managed-block file surgery
# ---------------------------------------------------------------------------


def install_managed_block(custom_path: Path, managed_content: str) -> None:
    """Write the managed block into `custom_path`.

    - File doesn't exist → create with `<systemList>` + managed block.
    - File exists with managed block → replace block in place.
    - File exists without managed block → insert block before `</systemList>`.

    Hand-edited content outside the managed block is preserved.
    """
    block = f"  {MANAGED_BLOCK_BEGIN}\n{managed_content}\n  {MANAGED_BLOCK_END}"

    custom_path.parent.mkdir(parents=True, exist_ok=True)

    if custom_path.exists():
        text = custom_path.read_text()
        if MANAGED_BLOCK_BEGIN in text:
            new_text = _MANAGED_BLOCK_RE.sub(_escape_re_replacement(block), text)
        else:
            new_text = _insert_before_close(text, block)
    else:
        new_text = f'<?xml version="1.0"?>\n<systemList>\n{block}\n</systemList>\n'

    custom_path.write_text(new_text)


def uninstall_managed_block(custom_path: Path) -> bool:
    """Strip the managed block from `custom_path`. Returns True if removed.

    If the resulting file has no remaining `<system>` entries (just an
    empty `<systemList>`), the file is left in place — ES-DE handles
    empty system lists fine, and removing the file would risk taking
    out structure the user wants to keep.
    """
    if not custom_path.is_file():
        return False
    text = custom_path.read_text()
    if MANAGED_BLOCK_BEGIN not in text:
        return False
    new_text = _MANAGED_BLOCK_RE.sub("", text)
    # Tidy up: remove any blank line left where the block sat.
    new_text = re.sub(r"\n[ \t]*\n[ \t]*\n", "\n\n", new_text)
    custom_path.write_text(new_text)
    return True


def _insert_before_close(text: str, block: str) -> str:
    """Insert `block` immediately before the closing `</systemList>` tag."""
    close_tag = "</systemList>"
    idx = text.rfind(close_tag)
    if idx == -1:
        raise ValueError(
            "custom_systems/es_systems.xml is missing a closing </systemList> tag; "
            "ferry won't modify malformed files"
        )
    return text[:idx] + block + "\n" + text[idx:]


def _escape_re_replacement(s: str) -> str:
    """Escape backslashes in `s` so `re.sub` treats it literally."""
    return s.replace("\\", "\\\\")
